---

- name: platform dependent vars
  include_vars: "{{ item }}"
  loop: "{{ query('first_found', params, errors='ignore') }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_system }}.yml"
      paths:
        - '{{ role_path }}/vars/platform'
  tags: always

- name: establish package
  become: true
  package:
    name: "{{ pip_executable_package }}"
    state: present
  tags: install

- name: establish packages
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    virtualenv_python: "{{ item.virtualenv_python | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ item.virtualenv is undefined | ternary(item.executable | default((pip_version | int < 3) | ternary('pip2','pip3')), omit) }}"
    editable: "{{ item.editable | default(omit) }}"
  loop: "{{ pip_packages }}"
  tags: install
